--
-- PostgreSQL database dump
--

\restrict BJvaq4SHodbo2czbo6HO6ENw2H01f5RQAXnZ7rNUyah8Fxoez0DwuU5xo0htvBV

-- Dumped from database version 18.3 (Debian 18.3-1.pgdg13+1)
-- Dumped by pg_dump version 18.3 (Debian 18.3-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: avaliacao_erros; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.avaliacao_erros (
    id_erro integer NOT NULL,
    id_avaliacao integer NOT NULL,
    tipo_erro character varying(80) NOT NULL,
    severidade character varying(20) NOT NULL,
    descricao text NOT NULL,
    trecho_resposta text,
    trecho_justificativa_juiz text,
    impacto_na_nota numeric(6,2),
    recomendado_ajuste_rubrica boolean DEFAULT false NOT NULL,
    criado_em timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT avaliacao_erros_severidade_check CHECK (((severidade)::text = ANY ((ARRAY['baixa'::character varying, 'media'::character varying, 'alta'::character varying, 'critica'::character varying])::text[])))
);


--
-- Name: avaliacao_erros_id_erro_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.avaliacao_erros ALTER COLUMN id_erro ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.avaliacao_erros_id_erro_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: avaliacoes_juiz; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.avaliacoes_juiz (
    id_avaliacao integer NOT NULL,
    id_resposta_ativa1 integer NOT NULL,
    id_modelo_juiz integer NOT NULL,
    nota_atribuida integer NOT NULL,
    prompt_juiz text NOT NULL,
    rubrica_utilizada text NOT NULL,
    chain_of_thought text NOT NULL,
    data_avaliacao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    papel_juiz character varying(20),
    rodada_julgamento character varying(30),
    motivo_acionamento text,
    id_resposta_auxiliar integer,
    CONSTRAINT avaliacoes_juiz_nota_atribuida_check CHECK (((nota_atribuida >= 1) AND (nota_atribuida <= 5))),
    CONSTRAINT avaliacoes_juiz_papel_juiz_check CHECK (((papel_juiz IS NULL) OR ((papel_juiz)::text = ANY ((ARRAY['principal'::character varying, 'controle'::character varying, 'arbitro'::character varying])::text[])))),
    CONSTRAINT avaliacoes_juiz_rodada_julgamento_check CHECK (((rodada_julgamento IS NULL) OR ((rodada_julgamento)::text = ANY ((ARRAY['padrao'::character varying, 'controle_qualidade'::character varying, 'arbitragem'::character varying])::text[]))))
);


--
-- Name: avaliacoes_juiz_id_avaliacao_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.avaliacoes_juiz_id_avaliacao_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: avaliacoes_juiz_id_avaliacao_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.avaliacoes_juiz_id_avaliacao_seq OWNED BY public.avaliacoes_juiz.id_avaliacao;


--
-- Name: datasets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.datasets (
    id_dataset integer NOT NULL,
    nome_dataset character varying(100) NOT NULL,
    dominio character varying(50) NOT NULL
);


--
-- Name: datasets_id_dataset_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.datasets_id_dataset_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: datasets_id_dataset_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.datasets_id_dataset_seq OWNED BY public.datasets.id_dataset;


--
-- Name: decisoes_finais_julgamento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.decisoes_finais_julgamento (
    id_decisao_final integer NOT NULL,
    id_resposta_ativa1 integer NOT NULL,
    nota_final numeric(6,2) NOT NULL,
    metodo_decisao character varying(30) NOT NULL,
    id_avaliacao_principal integer,
    id_avaliacao_controle integer,
    id_avaliacao_arbitro integer,
    divergencia_detectada boolean DEFAULT false NOT NULL,
    diferenca_notas numeric(6,2),
    arbitragem_acionada boolean DEFAULT false NOT NULL,
    motivo_arbitragem text,
    justificativa_decisao text,
    data_decisao timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT decisoes_finais_julgamento_metodo_decisao_check CHECK (((metodo_decisao)::text = ANY ((ARRAY['juiz_principal'::character varying, 'mediana_juizes'::character varying, 'decisao_arbitro'::character varying])::text[]))),
    CONSTRAINT decisoes_finais_julgamento_nota_final_check CHECK (((nota_final >= (1)::numeric) AND (nota_final <= (5)::numeric)))
);


--
-- Name: decisoes_finais_julgamento_id_decisao_final_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.decisoes_finais_julgamento ALTER COLUMN id_decisao_final ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.decisoes_finais_julgamento_id_decisao_final_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: human_audits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.human_audits (
    id_auditoria integer NOT NULL,
    id_avaliacao integer NOT NULL,
    auditor_nome character varying(120) NOT NULL,
    concorda_com_juiz boolean NOT NULL,
    nota_humana numeric(6,2),
    comentario text,
    erro_do_juiz_detectado boolean DEFAULT false NOT NULL,
    tipo_erro_juiz character varying(80),
    criado_em timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT human_audits_nota_humana_check CHECK (((nota_humana IS NULL) OR ((nota_humana >= (1)::numeric) AND (nota_humana <= (5)::numeric))))
);


--
-- Name: human_audits_id_auditoria_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.human_audits ALTER COLUMN id_auditoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.human_audits_id_auditoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: modelos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.modelos (
    id_modelo integer NOT NULL,
    nome_modelo character varying(100) NOT NULL,
    versao character varying(50),
    parametro_precisao character varying(20),
    tipo_modelo character varying(20) NOT NULL,
    CONSTRAINT modelos_tipo_modelo_check CHECK (((tipo_modelo)::text = ANY (ARRAY[('candidato'::character varying)::text, ('juiz'::character varying)::text, ('ambos'::character varying)::text])))
);


--
-- Name: modelos_id_modelo_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.modelos_id_modelo_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: modelos_id_modelo_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.modelos_id_modelo_seq OWNED BY public.modelos.id_modelo;


--
-- Name: perguntas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.perguntas (
    id_pergunta integer NOT NULL,
    id_dataset integer NOT NULL,
    enunciado text NOT NULL,
    resposta_ouro text NOT NULL,
    metadados jsonb
);


--
-- Name: perguntas_id_pergunta_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.perguntas_id_pergunta_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: perguntas_id_pergunta_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.perguntas_id_pergunta_seq OWNED BY public.perguntas.id_pergunta;


--
-- Name: respostas_atividade_1; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.respostas_atividade_1 (
    id_resposta integer NOT NULL,
    id_pergunta integer NOT NULL,
    id_modelo integer NOT NULL,
    texto_resposta text NOT NULL,
    tempo_inferencia_ms double precision,
    data_geracao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT respostas_atividade_1_tempo_inferencia_ms_check CHECK ((tempo_inferencia_ms >= (0)::double precision))
);


--
-- Name: respostas_atividade_1_id_resposta_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.respostas_atividade_1_id_resposta_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: respostas_atividade_1_id_resposta_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.respostas_atividade_1_id_resposta_seq OWNED BY public.respostas_atividade_1.id_resposta;


--
-- Name: respostas_auxiliares_juiz; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.respostas_auxiliares_juiz (
    id_resposta_auxiliar integer NOT NULL,
    id_pergunta integer NOT NULL,
    id_modelo_juiz integer NOT NULL,
    texto_resposta text NOT NULL,
    objetivo character varying(40) NOT NULL,
    prompt_utilizado text,
    versao_prompt character varying(50) NOT NULL,
    parametros_geracao jsonb,
    tempo_inferencia_ms double precision,
    finish_reason character varying(80),
    observacoes jsonb,
    data_geracao timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT respostas_auxiliares_juiz_objetivo_check CHECK (((objetivo)::text = ANY ((ARRAY['auditoria'::character varying, 'comparacao_entre_juizes'::character varying, 'calibracao_rubrica'::character varying])::text[]))),
    CONSTRAINT respostas_auxiliares_juiz_tempo_check CHECK (((tempo_inferencia_ms IS NULL) OR (tempo_inferencia_ms >= (0)::double precision)))
);


--
-- Name: respostas_auxiliares_juiz_id_resposta_auxiliar_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.respostas_auxiliares_juiz ALTER COLUMN id_resposta_auxiliar ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.respostas_auxiliares_juiz_id_resposta_auxiliar_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: avaliacoes_juiz id_avaliacao; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.avaliacoes_juiz ALTER COLUMN id_avaliacao SET DEFAULT nextval('public.avaliacoes_juiz_id_avaliacao_seq'::regclass);


--
-- Name: datasets id_dataset; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.datasets ALTER COLUMN id_dataset SET DEFAULT nextval('public.datasets_id_dataset_seq'::regclass);


--
-- Name: modelos id_modelo; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.modelos ALTER COLUMN id_modelo SET DEFAULT nextval('public.modelos_id_modelo_seq'::regclass);


--
-- Name: perguntas id_pergunta; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perguntas ALTER COLUMN id_pergunta SET DEFAULT nextval('public.perguntas_id_pergunta_seq'::regclass);


--
-- Name: respostas_atividade_1 id_resposta; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.respostas_atividade_1 ALTER COLUMN id_resposta SET DEFAULT nextval('public.respostas_atividade_1_id_resposta_seq'::regclass);


--
-- Name: avaliacao_erros avaliacao_erros_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.avaliacao_erros
    ADD CONSTRAINT avaliacao_erros_pkey PRIMARY KEY (id_erro);


--
-- Name: avaliacoes_juiz avaliacoes_juiz_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.avaliacoes_juiz
    ADD CONSTRAINT avaliacoes_juiz_pkey PRIMARY KEY (id_avaliacao);


--
-- Name: datasets datasets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.datasets
    ADD CONSTRAINT datasets_pkey PRIMARY KEY (id_dataset);


--
-- Name: decisoes_finais_julgamento decisoes_finais_julgamento_id_resposta_ativa1_uk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decisoes_finais_julgamento
    ADD CONSTRAINT decisoes_finais_julgamento_id_resposta_ativa1_uk UNIQUE (id_resposta_ativa1);


--
-- Name: decisoes_finais_julgamento decisoes_finais_julgamento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decisoes_finais_julgamento
    ADD CONSTRAINT decisoes_finais_julgamento_pkey PRIMARY KEY (id_decisao_final);


--
-- Name: human_audits human_audits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.human_audits
    ADD CONSTRAINT human_audits_pkey PRIMARY KEY (id_auditoria);


--
-- Name: modelos modelos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.modelos
    ADD CONSTRAINT modelos_pkey PRIMARY KEY (id_modelo);


--
-- Name: perguntas perguntas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perguntas
    ADD CONSTRAINT perguntas_pkey PRIMARY KEY (id_pergunta);


--
-- Name: respostas_atividade_1 respostas_atividade_1_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.respostas_atividade_1
    ADD CONSTRAINT respostas_atividade_1_pkey PRIMARY KEY (id_resposta);


--
-- Name: respostas_auxiliares_juiz respostas_auxiliares_juiz_pergunta_modelo_objetivo_prompt_uk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.respostas_auxiliares_juiz
    ADD CONSTRAINT respostas_auxiliares_juiz_pergunta_modelo_objetivo_prompt_uk UNIQUE (id_pergunta, id_modelo_juiz, objetivo, versao_prompt);


--
-- Name: respostas_auxiliares_juiz respostas_auxiliares_juiz_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.respostas_auxiliares_juiz
    ADD CONSTRAINT respostas_auxiliares_juiz_pkey PRIMARY KEY (id_resposta_auxiliar);


--
-- Name: idx_avaliacao_erros_id_avaliacao; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_avaliacao_erros_id_avaliacao ON public.avaliacao_erros USING btree (id_avaliacao);


--
-- Name: idx_avaliacao_erros_severidade; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_avaliacao_erros_severidade ON public.avaliacao_erros USING btree (severidade);


--
-- Name: idx_avaliacao_erros_tipo_erro; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_avaliacao_erros_tipo_erro ON public.avaliacao_erros USING btree (tipo_erro);


--
-- Name: idx_avaliacoes_juiz; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_avaliacoes_juiz ON public.avaliacoes_juiz USING btree (id_modelo_juiz);


--
-- Name: idx_avaliacoes_juiz_papel_juiz; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_avaliacoes_juiz_papel_juiz ON public.avaliacoes_juiz USING btree (papel_juiz);


--
-- Name: idx_avaliacoes_juiz_rodada_julgamento; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_avaliacoes_juiz_rodada_julgamento ON public.avaliacoes_juiz USING btree (rodada_julgamento);


--
-- Name: idx_avaliacoes_resposta; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_avaliacoes_resposta ON public.avaliacoes_juiz USING btree (id_resposta_ativa1);


--
-- Name: idx_decisoes_finais_julgamento_id_resposta_ativa1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_decisoes_finais_julgamento_id_resposta_ativa1 ON public.decisoes_finais_julgamento USING btree (id_resposta_ativa1);


--
-- Name: idx_human_audits_id_avaliacao; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_human_audits_id_avaliacao ON public.human_audits USING btree (id_avaliacao);


--
-- Name: idx_perguntas_dataset; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_perguntas_dataset ON public.perguntas USING btree (id_dataset);


--
-- Name: idx_respostas_auxiliares_juiz_pergunta_modelo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_respostas_auxiliares_juiz_pergunta_modelo ON public.respostas_auxiliares_juiz USING btree (id_pergunta, id_modelo_juiz);


--
-- Name: idx_respostas_modelo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_respostas_modelo ON public.respostas_atividade_1 USING btree (id_modelo);


--
-- Name: idx_respostas_pergunta; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_respostas_pergunta ON public.respostas_atividade_1 USING btree (id_pergunta);


--
-- Name: avaliacao_erros avaliacao_erros_id_avaliacao_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.avaliacao_erros
    ADD CONSTRAINT avaliacao_erros_id_avaliacao_fkey FOREIGN KEY (id_avaliacao) REFERENCES public.avaliacoes_juiz(id_avaliacao) ON DELETE CASCADE;


--
-- Name: avaliacoes_juiz avaliacoes_juiz_id_modelo_juiz_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.avaliacoes_juiz
    ADD CONSTRAINT avaliacoes_juiz_id_modelo_juiz_fkey FOREIGN KEY (id_modelo_juiz) REFERENCES public.modelos(id_modelo);


--
-- Name: avaliacoes_juiz avaliacoes_juiz_id_resposta_ativa1_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.avaliacoes_juiz
    ADD CONSTRAINT avaliacoes_juiz_id_resposta_ativa1_fkey FOREIGN KEY (id_resposta_ativa1) REFERENCES public.respostas_atividade_1(id_resposta);


--
-- Name: avaliacoes_juiz avaliacoes_juiz_id_resposta_auxiliar_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.avaliacoes_juiz
    ADD CONSTRAINT avaliacoes_juiz_id_resposta_auxiliar_fkey FOREIGN KEY (id_resposta_auxiliar) REFERENCES public.respostas_auxiliares_juiz(id_resposta_auxiliar);


--
-- Name: decisoes_finais_julgamento decisoes_finais_julgamento_id_avaliacao_arbitro_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decisoes_finais_julgamento
    ADD CONSTRAINT decisoes_finais_julgamento_id_avaliacao_arbitro_fkey FOREIGN KEY (id_avaliacao_arbitro) REFERENCES public.avaliacoes_juiz(id_avaliacao);


--
-- Name: decisoes_finais_julgamento decisoes_finais_julgamento_id_avaliacao_controle_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decisoes_finais_julgamento
    ADD CONSTRAINT decisoes_finais_julgamento_id_avaliacao_controle_fkey FOREIGN KEY (id_avaliacao_controle) REFERENCES public.avaliacoes_juiz(id_avaliacao);


--
-- Name: decisoes_finais_julgamento decisoes_finais_julgamento_id_avaliacao_principal_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decisoes_finais_julgamento
    ADD CONSTRAINT decisoes_finais_julgamento_id_avaliacao_principal_fkey FOREIGN KEY (id_avaliacao_principal) REFERENCES public.avaliacoes_juiz(id_avaliacao);


--
-- Name: decisoes_finais_julgamento decisoes_finais_julgamento_id_resposta_ativa1_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decisoes_finais_julgamento
    ADD CONSTRAINT decisoes_finais_julgamento_id_resposta_ativa1_fkey FOREIGN KEY (id_resposta_ativa1) REFERENCES public.respostas_atividade_1(id_resposta);


--
-- Name: human_audits human_audits_id_avaliacao_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.human_audits
    ADD CONSTRAINT human_audits_id_avaliacao_fkey FOREIGN KEY (id_avaliacao) REFERENCES public.avaliacoes_juiz(id_avaliacao) ON DELETE CASCADE;


--
-- Name: perguntas perguntas_id_dataset_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perguntas
    ADD CONSTRAINT perguntas_id_dataset_fkey FOREIGN KEY (id_dataset) REFERENCES public.datasets(id_dataset);


--
-- Name: respostas_atividade_1 respostas_atividade_1_id_modelo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.respostas_atividade_1
    ADD CONSTRAINT respostas_atividade_1_id_modelo_fkey FOREIGN KEY (id_modelo) REFERENCES public.modelos(id_modelo);


--
-- Name: respostas_atividade_1 respostas_atividade_1_id_pergunta_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.respostas_atividade_1
    ADD CONSTRAINT respostas_atividade_1_id_pergunta_fkey FOREIGN KEY (id_pergunta) REFERENCES public.perguntas(id_pergunta);


--
-- Name: respostas_auxiliares_juiz respostas_auxiliares_juiz_id_modelo_juiz_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.respostas_auxiliares_juiz
    ADD CONSTRAINT respostas_auxiliares_juiz_id_modelo_juiz_fkey FOREIGN KEY (id_modelo_juiz) REFERENCES public.modelos(id_modelo);


--
-- Name: respostas_auxiliares_juiz respostas_auxiliares_juiz_id_pergunta_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.respostas_auxiliares_juiz
    ADD CONSTRAINT respostas_auxiliares_juiz_id_pergunta_fkey FOREIGN KEY (id_pergunta) REFERENCES public.perguntas(id_pergunta);


--
-- PostgreSQL database dump complete
--

\unrestrict BJvaq4SHodbo2czbo6HO6ENw2H01f5RQAXnZ7rNUyah8Fxoez0DwuU5xo0htvBV

